### ISSUE TITLE
How much better is MFFD compared to FFD?

### ISSUE THREAD

**Issue by LowLevelMahn** [rwjs/pybinpack#1]
i've implemented the MFFD algorithm in C/C++ based on the original paper: https://core.ac.uk/download/pdf/82682684.pdf (page: 68/69)
(and your code as a small guidance)

my current results are: FFD always beats MFFD

did you come to a similar conclusion?
i currently got problems to understand where MFFD real can shine

btw: your code only seem to implement four steps but there are actually 5 steps in the paper
(in think your code is missing the B-item assignment in step 2 of the paper)

**Comment by LowLevelMahn** [comment]
my FFD and MFFD are very similar (except much more code for MFFD) but your MFFD implementation needs usually more space then my MFFD implementation

my FFD: 109
my MFFD: 109
your FFD: 109
your MFFD: 112

**Comment by rwjs** [comment]
It's been a while - but I implemented step 2 by reversing the list up-front ([mffd.py:L79](https://github.com/rwjs/pybinpack/blob/master/lib/mffd.py#L79)). The original description specified descending order ([mffd.py:L47-48](https://github.com/rwjs/pybinpack/blob/master/lib/mffd.py#L47)), but I've used ascending order. These should be equivalent;

```
# My approach
lst_in = [1,2,3] # Ascending order
lst_out = []
while lst_in:
    lst_out.append(lst_in.pop(0)) # append+pop(0) maintains order

print(lst_out)
>>> [1,2,3]

# Original approach
lst_in = [3,2,1] # Descending order
lst_out = []
while lst_in:
    lst_out.append(lst_in.pop(0)) # append+pop(0) maintains order

lst_out.reverse() # Explicit reverse [Step #2]
print(lst_out)
>>> [3,2,1]
```

My approach makes it a lot less clumsy to find the two smallest items in step #3 - lst_c also ends up ordered ascending, so I can just instantiate index_c1 and index_c2 as 0 and 1, and those will naturally be the two smallest ([mffd.py:L122-123](https://github.com/rwjs/pybinpack/blob/master/lib/mffd.py#L122)).

As to where MFFD might be better - it's only got a better worst-case bound, not a guaranteed improvement on FFD. FFD might produce better results against any given sample, but the theory says it _may_ produce a worse result for some sample. Do you have a gist or description of how you're generating your test samples?

If you're able to share your implementation, it would be helpful for me to see why it differs from mine - particularly since you've sourced the original paper, but my reference was primarily comments from a Haskell implementation ( now at http://hackage.haskell.org/package/Binpack-0.3.1/src/Data/BinPack.hs ).

**Comment by LowLevelMahn** [comment]
my complete code: https://gist.github.com/LowLevelMahn/17c0d2cc3ecad74fd2d3f6921c2b3445
its memory usage optimized C/C++ code - a little hard to read - but includes the test sample generation and the complete code - i can reduce it down to a more vanilla version if that is too much code

**Comment by LowLevelMahn** [comment]
reduced the C++ Code a little, third time update

**Comment by LowLevelMahn** [comment]
i use "ranges" to optimize memory movement/usage (its for an embedded system)

![image](https://user-images.githubusercontent.com/580819/81798649-93359880-9510-11ea-8e95-2d57250537aa.png)
